import math
import numpy as np
from ngsolve import Mesh, TaskManager, H1, HCurl, FESpace, Periodic
from ngsolve import GridFunction, BilinearForm, LinearForm
from ngsolve import CF, grad, curl, dx, ds, Cross, Conj, x, y, IfPos

class FEMSolver2D:
    def __init__(self, config, mesh: Mesh, stix_physics, pml_physics, waveguide_physics):
        """
        Initializes the 2D Orchestrator.
        Args:
            config: SimulationConfig (from yaml)
            mesh: The 2D mesh generated by MeshFactory
            stix_physics: Instantiated StixPhysics module
            pml_physics: Instantiated JacquotPML module
            waveguide_physics: Instantiated WaveguidePhysics module
        """
        self.config = config
        self.mesh = mesh
        self.stix = stix_physics
        self.pml = pml_physics
        self.wg = waveguide_physics
        
        # Fundamental Constants
        self.k0 = self.config.physics.wave.k0
        self.omega = self.config.physics.wave.omega_LH
        self.mu0 = 4 * math.pi * 1e-7
        self.eps0 = 1 / (self.mu0 * 299792458.0**2)
        
        # In NGSolve 2D, the physical toroidal axis (z) maps to the solver's 'y' coordinate.
        # The physical poloidal axis (physical y-coord) is the out-of-plane component.
        self.radial_var = x 
        self.toroidal_var = y 
        
        # Data containers
        self.fes = None
        self.E_field = None
        
    def _compute_edge_admittance(self):
        """
        Computes the theoretical surface admittance tensor Y (2x2) at the antenna/plasma 
        interface (x=0) to construct the Robin boundary condition.
        """
        # Extract edge density from the yaml profile
        ne_edge = self.config.physics.plasma.radial_density_profile.points[0][1]
        
        if self.config.simulation.box_medium == "VACUUM":
            n_para = self.config.physics.wave.n_para_req
            n_perp_vac = np.sqrt(complex(1.0 - n_para**2))
            Z0 = np.sqrt(self.mu0 / self.eps0)
            
            # Pure TM wave admittance in vacuum
            self.Y_11 = self.Y_22 = 0.0 + 0.0j
            self.Y_12 = 1.0 / (n_perp_vac * Z0)
            self.Y_21 = -1.0 / (n_perp_vac * Z0)
            
            self.edge_n_perp_p = n_perp_vac
            self.edge_S = self.edge_D = self.edge_P = 1.0 # Vacuum placeholder
            return

        # ---------------------------------------------------------
        # Plasma Edge Roots of dispersion Relation (=Booker Equation)
        # ---------------------------------------------------------
        # Evaluate the roots of the Booker quartic (assuption=constant density plasma)
        # specifically using ne_edge and the local B-field to find n_perp_p (Slow Wave) 
        # and n_perp_m (Fast Wave). 
        # (Assuming a helper function `solve_booker(ne, B)` exists in StixPhysics)
        
        edge_params = self.stix.solve_booker(ne_edge)
        self.edge_S = edge_params["S"]
        self.edge_D = edge_params["D"]
        self.edge_P = edge_params["P"]
        self.edge_n_perp_p = edge_params["n_perp_p"] # Slow wave
        self.edge_n_perp_m = edge_params["n_perp_m"] # Fast wave
        
        n_para = self.config.physics.wave.n_para_req
        Z0 = np.sqrt(self.mu0 / self.eps0)
        
        # Cold plasma admittance tensor components
        Py_S = (1j * self.edge_D * (self.edge_n_perp_p**2 - self.edge_P)) / \
               (self.edge_n_perp_p * n_para * (self.edge_n_perp_p**2 - self.edge_S))
        Py_F = (1j * self.edge_D * (self.edge_n_perp_m**2 - self.edge_P)) / \
               (self.edge_n_perp_m * n_para * (self.edge_n_perp_m**2 - self.edge_S))
        
        denom = Z0 * (Py_S - Py_F)
        self.Y_11 = (-self.edge_P/self.edge_n_perp_p + self.edge_P/self.edge_n_perp_m) / denom
        self.Y_12 = -(self.edge_P*Py_F/self.edge_n_perp_p - self.edge_P*Py_S/self.edge_n_perp_m) / denom
        self.Y_21 = -(self.edge_n_perp_p*Py_S - self.edge_n_perp_m*Py_F) / denom
        self.Y_22 = (Py_S*Py_F*(self.edge_n_perp_m - self.edge_n_perp_p)) / denom

    def _setup_function_spaces(self):
        """
        Dynamically builds the H(curl) x H1 spaces based on yaml boundary conditions.
        """
        # Determine Dirichlet (PEC) boundaries dynamically
        dirichlet_tags = ["bottom_wall_pec"]
        
        # Radial PML usually absorbs, but its outer wall is PEC
        if self.config.geometry.pml.use_radial:
            dirichlet_tags.append("top_wall_pec")
            
        # Toroidal Boundaries
        bc_toroidal = self.config.simulation.boundary_toroidal
        if bc_toroidal in ["pec", "pml"]:
            dirichlet_tags.extend(["left_wall_pec", "right_wall_pec"])
            
        dirichlet_str = "|".join(dirichlet_tags)
        order = self.config.solver.fem_order
        
        # Base spaces
        fes_in_plane = HCurl(self.mesh, order=order, complex=True, dirichlet=dirichlet_str)
        fes_out_plane = H1(self.mesh, order=order, complex=True, dirichlet=dirichlet_str)
        
        # Apply periodic wrappers if defined in yaml and tagged in mesh_builder
        if bc_toroidal == "periodic":
            fes_in_plane = Periodic(fes_in_plane)
            fes_out_plane = Periodic(fes_out_plane)
            
        # Unified Product Space
        self.fes = fes_in_plane * fes_out_plane
        print(f'==== #DoFs = {self.fes.ndof}')
        self.E_field = GridFunction(self.fes)

    def _build_physics_tensors(self):
        """Combines the Pitch-Angle Rotated Stix Tensor with the PML metric."""
        
        # 1. Get raw cold plasma parameters (S, D, P)
        stix_dict = self.stix.get_stix_parameters()
        S, D, P = stix_dict["S"], stix_dict["D"], stix_dict["P"]
        
        # 2. Construct the full 3x3 Dielectric Tensor K (Pitch Angle Rotation)
        # Assuming a flat B-field for simplicity here; ideally driven by the profile
        pitch_rad = math.radians(self.config.physics.plasma.pitch_angle_profile.points[0][1])
        bx, by, bz = 0.0, math.sin(pitch_rad), math.cos(pitch_rad)
        
        Q = P - S
        K_xx = S*(1 - bx**2) + P*bx**2
        K_xy = 1j*D*bz + Q*bx*by
        K_xz = -1j*D*by + Q*bx*bz
        K_yx = -1j*D*bz + Q*by*bx
        K_yy = S*(1 - by**2) + P*by**2
        K_yz = 1j*D*bx + Q*by*bz
        K_zx = 1j*D*by + Q*bz*bx
        K_zy = -1j*D*bx + Q*bz*by
        K_zz = S*(1 - bz**2) + P*bz**2
        
        K_tensor = CF((K_xx, K_xy, K_xz, K_yx, K_yy, K_yz, K_zx, K_zy, K_zz), dims=(3,3))
        
        # 3. Apply PML metrics
        self.Lambda_curl = self.pml.get_curl_tensor()
        self.Lambda_eps = self.pml.get_effective_dielectric_tensor(K_tensor)

    def solve(self):
        """Assembles the matrices and solves the Weak Formulation."""
        self._compute_edge_admittance()
        self._setup_function_spaces()
        self._build_physics_tensors()
        print('admittance computed,\n function spaces set up, \n physics tensor built')
        # Trial and Test Functions
        E_plane, E_outplane = self.fes.TrialFunction()
        v_plane, v_outplane = self.fes.TestFunction()
        
        # Map 2D software variables to 3D physical vectors
        # NGSolve plane = (x, y_solver). Physics = (x, z_physics)
        E_3D = CF((E_plane[0], E_outplane, E_plane[1])) 
        v_3D = CF((v_plane[0], v_outplane, v_plane[1]))
        
        # Curl mapping: (dEy/dz, dEx/dz - dEz/dx, -dEy/dx)
        curl_E_3D = CF(( E_outplane.Deriv()[1], curl(E_plane), -E_outplane.Deriv()[0] ))
        curl_v_3D = CF(( v_outplane.Deriv()[1], curl(v_plane), -v_outplane.Deriv()[0] ))

        # ---------------------------------------------------------
        # Bilinear Form (Matrix A)
        # ---------------------------------------------------------
        a = BilinearForm(self.fes)
        
        # Volume Integrals (PDE)
        a += (self.Lambda_curl * curl_E_3D * curl_v_3D - \
              self.k0**2 * self.Lambda_eps * E_3D * v_3D) * dx
              
        # Boundary Integrals (Robin Admittance at x=0)
        Ez_trace, Ey_trace = E_plane.Trace()[1], E_outplane.Trace()
        vz_trace, vy_trace = v_plane.Trace()[1], v_outplane.Trace()
        
        # Absorbing/Transmitting term for both active and passive waveguides
        admittance_term = (self.Y_21 * Ey_trace + self.Y_22 * Ez_trace) * vy_trace - \
                          (self.Y_11 * Ey_trace + self.Y_12 * Ez_trace) * vz_trace
                          
        # We apply this to both active and passive source tags defined in mesh_builder
        a += 2j * self.omega * self.mu0 * admittance_term * ds("bottom_source_active|bottom_source_passive")

        # ---------------------------------------------------------
        # Linear Form (Vector f)
        # ---------------------------------------------------------
        f = LinearForm(self.fes)
        
        # Get active port excitations (Only applied to "bottom_source_active")
        # In a fully rigorous solver, we map the list of ports to their spatial z-coordinates
        # Here we use a continuous spatial mapping function similar to your old code
        Ez_inc_spatial = self.wg.build_spatial_source_function(self.toroidal_var) 
        
        # Calculate Incident Magnetic Field from Ez_inc
        # (Assuming vacuum waveguide mode mapping)
        Z0 = np.sqrt(self.mu0 / self.eps0)
        Hy_inc = -(1.0 / Z0) * Ez_inc_spatial 
        Hz_inc = CF(0.0 + 0.0j)
        Ey_inc = CF(0.0 + 0.0j)
        
        Ay = (self.Y_11 * Ey_inc + self.Y_12 * Ez_inc_spatial) - Hy_inc
        Az = (self.Y_21 * Ey_inc + self.Y_22 * Ez_inc_spatial) - Hz_inc
        
        source_injection = (Az * vy_trace - Ay * vz_trace)
        f += 1j * self.omega * self.mu0 * source_injection * ds("bottom_source_active")

        # ---------------------------------------------------------
        # Multithreaded Matrix Solution
        # ---------------------------------------------------------
        print('--- Weak Form Assembly ---')
        with TaskManager():
            a.Assemble()
            f.Assemble()
            
            res = f.vec.CreateVector()
            res.data = f.vec - a.mat * self.E_field.vec
            
            # Using the exact solver backend requested in yaml (e.g. "mumps")
            inv = a.mat.Inverse(freedofs=self.fes.FreeDofs()) #, inverse=self.config.solver.linear_backend)
            self.E_field.vec.data += inv * res
        print(f'--- System Solved ---')
        return self.E_field