# ==========================================
# ALOHA FEM - Input Configuration
# ==========================================

simulation:
  dimension: "2D"                 # "1D" (boundary only), "2D" (infinite height), "3D"
  mode: "DirectAperture"          # "DirectAperture" or "ExplicitGeometry"
  box_medium: "VACUUM"            #  "PLAMSA" or "VACUUM"

  boundary_toroidal: "pml"        # "periodic", "pec", or "pml"
  boundary_poloidal: "pec"        # "periodic", "pec", or "pml" (used in 3D)

physics:
  wave:
    freq_LH: 3.7e9
    n_para_req: 0.0               # Used for initial phasing estimates or 1D mode

  plasma:
    b_field_profile:
      type: "piecewise"
      points:
        - [0.00, 3.7]             # B field at the antenna mouth
        - ["Lx_plasma", 3.7]             # B field in the core
      segments:
        - "constant"

    pitch_angle_profile:
      type: "piecewise"
      points:
        - [0.00, 0.0]
        - ["Lx_plasma", 0.0]
      segments:
        - "constant"

    radial_density_profile:               # Piecewise radial profile builder
      type: "piecewise"
      points:                     # [x_position, electron_density]
        - [0.00, 5.0e17]             # Point 0: Antenna mouth
        - ["Lx_plasma", 5.0e17]   # Point 2: Core gradient end
      segments:                   # Mathematical link between points
        - "constant"                # Links Point 1 to Point 2

    use_perturbations: False
    perturbations:                # perturbation block
      - type: "gaussian_blob"
        amplitude: 8.0e17         # Positive for a blob, negative for a depletion
        x_c: 0.02                 # Radial center (m)
        z_c: 0.035                # Toroidal center (m)
        sigma_x: 0.005           # Radial width (m)
        sigma_z: 0.003             # Toroidal width (m)
      - type: "gaussian_blob"
        amplitude: -2.0e17        # A localized depletion
        x_c: 0.01
        z_c: 0.20
        sigma_x: 0.003
        sigma_z: 0.006

    toroidal_density_profile:             # Toroidally, the density might be flat, or have a slight ripple/gradient
      type: "constant"

geometry:
  domain:
    # The distance are given in meters (m)
    Lx_plasma: 0.1                # Radial size of the plasma domain
    Lx_pml: 0.03                  # Depth of the radial PML
    Lz_plasma: 0.1                # Lz_plasma depend on the antenna toroidal size
    Lz_pml: 0.05                  # Depth of the toroidal PMLs
    Lz_wall: 0.07                 # (m)
    Ly_plasma: 0.10               # (m) Poloidal height (required for 3D)
    Ly_pml: 0.05                  # (m)
    Ly_wall: 0.02                 # (m)


  mesh:
    ppw_medium: 5.0              # Points per wavelength in bulk
    ppw_pml: 10.0                 # Points per wavelength in PML
    grading: 0.15                 # Max element size growth rate (15%) for smoothed refinement

  pml:
    use_radial: true
    use_toroidal: true
    use_poloidal: false
    Sx_r: 2.0
    Sx_im: 2.0
    px: 2.5
    Sz_r: 1.88
    Sz_im: 4.0
    pz: 3.0

solver:
  fem_order: 3                    # Polynomial degree for Hcurl/H1 spaces
  linear_backend: "umfpack"         # Direct solver choice: "mumps", "umfpack", "pardiso"
  max_threads: 8                  # Number of OpenMP/NGSolve threads to allocate